### ISSUE TITLE
Add ability to create new projects

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/openshift-dd-ext#12]
It should be doable to add a "new project"
<img width="1045" alt="Screenshot 2022-04-19 at 16 44 25" src="https://user-images.githubusercontent.com/148698/164030997-11b7aa70-a8ca-4173-b8c6-acb537729492.png">
 button to the project selector:

**Comment by dgolovin** [comment]
![new-project-v1](https://user-images.githubusercontent.com/620330/164399198-7e0eaf06-4403-48b9-9930-39025e09a3aa.gif)

Still required:
* validation for existing names 
* validation the name is using valid character set
* `Create New` button on context card  after 'Change' button for project name (optional)
