### ISSUE TITLE
Provide tooltips on icon

### ISSUE THREAD

**Issue by slemeur** [redhat-developer/openshift-dd-ext#21]
As a user, the icons themselves are not going to be sufficient to tell me what actions are behind each buttons. 
It would be nicer to provide tooltips behind the button, so that the user can discover what's the button will do, without having to click on it.

**Comment by fbricon** [comment]
![Apr-25-2022 11-48-27](https://user-images.githubusercontent.com/148698/165068151-d44e1909-5e1e-47d5-9e7c-e1da7ee03fff.gif)
