### ISSUE TITLE
Navigating to different tab in Docker Desktop loose context in OpenShift extension

### ISSUE THREAD

**Issue by slemeur** [redhat-developer/openshift-dd-ext#22]
Ways to reproduce:
1- Start the process to deploy an image to openshift
2- Jump into another tab from Docker Desktop (like containers)
3- Navigate back into the OpenShift Extension

Actual behaviour:
- Context is lost and the user is back at the landing screen (intro to openshift). All selected information in the "Deploy to OpenShift" screen are lost.

Expected behavior:
- The context is not lost and user is finding the information already filled previously

**Comment by dgolovin** [comment]
There is not API for saving state. We can try to save it to file and restore state from file when extension is activated, but there is no API to access to file system ether. Workaround is to use Exec and read/change file using platform specific commands like cat/echo. Am I missing something @fbricon?

IIRC Docker Dashboard even kills exec commands started by extension if extension is deactivated. In this case starting (1) and doing (2) while (1) is still in progress, will kill (1) without waiting for it to finish, potentially leaving resources create in OpenShift cluster in error state.

**Comment by fbricon** [comment]
So #22 shows there's a really simple way to keep state during the session. As for DD killing exec commands, this orthogonal to this issue IMO, well have this problem no matter what

**Comment by dgolovin** [comment]
Resolved by using localState. The state persists between sessions. Navigate back to welcome page by clicking on OpenShift logo. SessionStorage persists values only when switching between extensions, activation of any non extension page resets the sessionStorage content.
