### ISSUE TITLE
Suggest to login to cluster when no contexts available to switch to

### ISSUE THREAD

**Issue by dgolovin** [redhat-developer/openshift-dd-ext#33]
![image](https://user-images.githubusercontent.com/620330/166826061-ad19d7c2-b207-4d0d-95d9-029eb5a8d4b2.png)

**Comment by fbricon** [comment]
disable or hide the "change context" button if there are no contexts available

**Comment by dgolovin** [comment]
That solves the problem, but UI still need to give user a hint what to do in this case.
