### ISSUE TITLE
Provide Description, Screenshots and Resources info for Extension's Marketplace page

### ISSUE THREAD

**Issue by dgolovin** [redhat-developer/openshift-dd-ext#35]
Currently it looks like this:

![image](https://user-images.githubusercontent.com/620330/166826850-9548b4ce-565e-4445-9455-7cf470531c3e.png)

**Comment by fbricon** [comment]
@dgolovin can we close it now?

<img width="1009" alt="Screenshot 2022-05-09 at 18 43 15" src="https://user-images.githubusercontent.com/148698/167457610-589542c1-f1be-4ff7-8441-852640b601e0.png">
