### ISSUE TITLE
Provide a way to sign up for a free OpenShift cluster on DevSandbox

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/openshift-dd-ext#46]
i.e. link to https://developers.redhat.com/developer-sandbox/get-started

**Comment by fbricon** [comment]
Test adding a button from the login dialog:

<img width="841" alt="Screenshot 2022-05-12 at 10 08 52" src="https://user-images.githubusercontent.com/148698/168023329-7a0927dd-b63e-4fa6-8d9b-f4f933d42652.png">

@slemeur @mohitsuman any comments? other/better ideas?

**Comment by slemeur** [comment]
Looks great to me to get that in the extension quickly!

**Comment by mohitsuman** [comment]
We should also add `Learn More` button and point to https://console.redhat.com/openshift/create, to see all the offerings supported by Red Hat.

**Comment by fbricon** [comment]
@mohitsuman agreed on principle but https://console.redhat.com/openshift/create access requires creating a Red Hat account 1st, so probably a no go. Need a publicly accessible URL

**Comment by fbricon** [comment]
@mohitsuman does https://www.redhat.com/en/technologies/cloud-computing/openshift work for you?

**Comment by mohitsuman** [comment]
I agree console.redhat needs RH authentication. We can use this then, https://www.redhat.com/en/technologies/cloud-computing/openshift/try-it
