### ISSUE TITLE
Creating Issues template for the project

### ISSUE THREAD

**Issue by vatana7** [redhat-developer/openshift-dd-ext#73]
I've created issues template for those who want to create new issues for an easier issues management inside this project. Please assign me to the task and I'll create PR immediately. Thanks!

-- Bugs report --
<img width="793" alt="image" src="https://user-images.githubusercontent.com/61142258/194718103-3b332802-3ef1-4fb6-8af4-0fe529e1b0e1.png">

-- Features request --
<img width="930" alt="image" src="https://user-images.githubusercontent.com/61142258/194718118-31575ad8-dc3b-4dbe-b73d-f0adc6a8233c.png">

**Comment by dgolovin** [comment]
@vatana7 thanks for volunteering! I'll review it shortly.

**Comment by dgolovin** [comment]
Released to main.
Thanks @vatana7 !
