### ISSUE TITLE
Getting "No exposed ports found", but `docker inspect` shows exposed port

### ISSUE THREAD

**Issue by DonSchenck** [redhat-developer/openshift-dd-ext#80]
**Describe the bug**
From PODMAN DESKTOP:
When deploying an image (quay.io/donschenck/qotd:v2) I get the message "No exposed ports found".
However, running `docker inspect quay.io/donschenck/qotd:v2` shows an exposed port (10000/tcp)

**To Reproduce**
1. Go to Deploy to OpenShift panel
2. Select quay.io/donschenck/qotd:v2 from my list of local images
3. Click "Deploy"
4. See final message in log

**Expected behavior**
Command `oc expose service/qotd` should be executed

**Additional context**
This is using PODMAN DESKTOP.
I *HAVE* created `alias docker=podman`

**Extension info**
Version: [redhatdeveloper/openshift-dd-ext:latest]
OS: macOS

**Comment by fbricon** [comment]
Works for me on **Docker Desktop**. I get this:

```
Deploying quay.io/donschenck/qotd:v2 to OpenShift...
--> Found container image 79204f7 (2 years old) from quay.io for "quay.io/donschenck/qotd:v2"
    * An image stream tag will be created as "qotd:v2" that will track this image
--> Creating resources ...
    imagestream.image.openshift.io "qotd" created
    deployment.apps "qotd" created
    service "qotd" created
--> Success
    Application is not exposed. You can expose services to the outside world by executing one or more of the commands below:
     'oc expose service/qotd' 
    Run 'oc status' to view your app.
route.route.openshift.io/qotd exposed

Application qotd exposed at http://qotd-fbricon-dev.apps.sandbox.x8i5.p1.openshiftapps.com
...
Application URL http://qotd-fbricon-dev.apps.sandbox.x8i5.p1.openshiftapps.com opened in browser
```

I need to check on podman desktop

**Comment by DonSchenck** [comment]
So the issue is Podman Desktop. Thanks.

Interestingly enough, the "Inspect" feature of Podman Desktop DOES show ExposedPorts and the value 10000.

**Comment by DonSchenck** [comment]
I upgraded to Podman Desktop 0.9.0 and Podman 4.3.0 and now everything works as intended.

This issue can be closed.
